[package]
name = "replicator_clickhouse"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { workspace = true, features = ["yaml"] }
pg_replicate = { path = "../pg_replicate", features = ["clickhouse"] }
rustls = { workspace = true, features = ["aws-lc-rs", "logging"] }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
rustls-pemfile = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true, default-features = true }
tracing-subscriber = { workspace = true, default-features = true, features = [
    "env-filter",
] }
