source:
  host: "172.17.0.1"
  port: 5432
  name: "postgres"
  username: "postgres"
  password: "password"
  slot_name: "stdout_slot"
  tls:
    trusted_root_certs: ""
    enabled: false
destination:
  click_house:
    url: "http://172.17.0.1:8123"
    database: "pgrep"
    username: "default"
    password: "password"
state_store:
  memory:
